version: '3'

services:
  db: 
    image: mongo:5
    restart: always
    container_name: seatext-chat
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: seatextDB
    volumes:
      - ./mongo:/data/db